---
- block: # Firewall Configuration for RedHat

  - name: Asegurandose que firewalld esta habilitado.
    systemd:
      name: firewalld
      state: started
      enabled: yes

  - name: Permitir uso del firewall.
    firewalld:
      service: "{{ item }}"
      permanent: true
      state: enabled
      immediate: yes
    with_items: "{{ gitlab_firewalld_allows }}"

  when: ansible_os_family == "RedHat"


- name: Instalar dependencias de GitLab.
  package:
    name: "{{ gitlab_package_dependencies }}"
    state: present
    update_cache: yes
  notify:
    - Start sshd

- name: Instalar Postfix.
  package:
    name: postfix
    state: present
  notify:
    - Start postfix
  when: not gitlab_use_external_smtp

- meta: flush_handlers

- name: Ejecutar script para comprobar si se ha agregado el repositorio de GitLab CE.
  shell: "curl -L -s {{ gitlab_script_url }} | bash"
  args:
    # Not to warn about using get_url
    warn: false